name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: 'soft'
    - name: Run tests
      run: cargo test --verbose
      working-directory: 'soft'
    - name: Lint
      run: cargo clippy -- -D warnings
      working-directory: 'soft'
    - name: Format check 
      run: cargo fmt -- --check
      working-directory: 'soft'

